const data = {
    products:[
        {
            _id:'1',
            name:'Nike slim shirt',
            category:'shirts',
            image:'/images/p1.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adidas slim shirt',
            category:'shirts',
            image:'/images/p2.jpg',
            price:200,
            brand:'Adidas',
            rating:4.6,
            numReviews:12,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'puma slim shirt',
            category:'shirts',
            image:'/images/p3.jpg',
            price:220,
            brand:'puma',
            rating:4.7,
            numReviews:14,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'uspolo free shirt',
            category:'shirts',
            image:'/images/p4.jpg',
            price:300,
            brand:'uspolo',
            rating:4.8,
            numReviews:16,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Roadster free shirt',
            category:'shirts',
            image:'/images/p5.jpg',
            price:320,
            brand:'Roadster',
            rating:4.9,
            numReviews:18,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'HRX fit shirt',
            category:'shirts',
            image:'/images/p6.jpg',
            price:400,
            brand:'HRX',
            rating:5.0,
            numReviews:20,
            description:'high quality product',
        },
    ],
};
export default data;